language: node_js
node_js:
  - node
install:
  - npm install
  - npm --prefix react-ui install
script:
  - npm run test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
